2021-05-27 12:18:38,150 INFO    MainThread:34438 [wandb_setup.py:_flush():69] setting env: {}
2021-05-27 12:18:38,151 INFO    MainThread:34438 [wandb_setup.py:_flush():69] setting login settings: {'api_key': 'f97918185ed02886a90fa4464e7469c13c017460'}
2021-05-27 12:18:38,151 INFO    MainThread:34438 [wandb_setup.py:_flush():69] setting login settings: {'api_key': 'f97918185ed02886a90fa4464e7469c13c017460'}
2021-05-27 12:18:38,151 INFO    MainThread:34438 [wandb_setup.py:_flush():69] setting login settings: {}
2021-05-27 12:18:38,151 INFO    MainThread:34438 [wandb_init.py:_log_setup():336] Logging user logs to /home/veror/Desktop/Uni/Applied Machine Learning/Challenge/ML_project/AutoencoderModel/wandb/run-20210527_121838-3kw2zd5q/logs/debug.log
2021-05-27 12:18:38,151 INFO    MainThread:34438 [wandb_init.py:_log_setup():337] Logging internal logs to /home/veror/Desktop/Uni/Applied Machine Learning/Challenge/ML_project/AutoencoderModel/wandb/run-20210527_121838-3kw2zd5q/logs/debug-internal.log
2021-05-27 12:18:38,152 INFO    MainThread:34438 [wandb_init.py:init():369] calling init triggers
2021-05-27 12:18:38,152 INFO    MainThread:34438 [wandb_init.py:init():374] wandb.init called with sweep_config: {}
config: {}
2021-05-27 12:18:38,152 INFO    MainThread:34438 [wandb_init.py:init():418] starting backend
2021-05-27 12:18:38,152 INFO    MainThread:34438 [backend.py:_multiprocessing_setup():70] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-05-27 12:18:38,164 INFO    MainThread:34438 [backend.py:ensure_launched():132] starting backend process...
2021-05-27 12:18:38,171 INFO    MainThread:34438 [backend.py:ensure_launched():136] started backend process with pid: 34464
2021-05-27 12:18:38,172 INFO    MainThread:34438 [wandb_init.py:init():423] backend started and connected
2021-05-27 12:18:38,174 INFO    MainThread:34438 [wandb_init.py:init():465] updated telemetry
2021-05-27 12:18:38,174 INFO    MainThread:34438 [wandb_init.py:init():484] communicating current version
2021-05-27 12:18:38,773 INFO    MainThread:34438 [wandb_init.py:init():489] got version response 
2021-05-27 12:18:38,773 INFO    MainThread:34438 [wandb_init.py:init():497] communicating run to backend with 30 second timeout
2021-05-27 12:18:38,999 INFO    MainThread:34438 [wandb_init.py:init():522] starting run threads in backend
2021-05-27 12:18:40,158 INFO    MainThread:34438 [wandb_run.py:_console_start():1565] atexit reg
2021-05-27 12:18:40,159 INFO    MainThread:34438 [wandb_run.py:_redirect():1412] redirect: SettingsConsole.REDIRECT
2021-05-27 12:18:40,159 INFO    MainThread:34438 [wandb_run.py:_redirect():1417] Redirecting console.
2021-05-27 12:18:40,160 INFO    MainThread:34438 [wandb_run.py:_redirect():1479] Redirects installed.
2021-05-27 12:18:40,160 INFO    MainThread:34438 [wandb_init.py:init():546] run started, returning control to user process
2021-05-27 12:18:40,161 INFO    MainThread:34438 [wandb_config.py:__setitem__():141] config set epochs = 11 - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x7f084a3609a0>>
2021-05-27 12:18:40,161 INFO    MainThread:34438 [wandb_run.py:_config_callback():787] config_cb epochs 11 None
2021-05-27 12:18:40,161 INFO    MainThread:34438 [wandb_config.py:__setitem__():141] config set batch_size = 3 - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x7f084a3609a0>>
2021-05-27 12:18:40,161 INFO    MainThread:34438 [wandb_run.py:_config_callback():787] config_cb batch_size 3 None
2021-05-27 12:18:59,348 INFO    MainThread:34438 [wandb_run.py:_atexit_cleanup():1535] got exitcode: 0
2021-05-27 12:18:59,353 INFO    MainThread:34438 [wandb_run.py:_restore():1507] restore
2021-05-27 12:19:01,357 INFO    MainThread:34438 [wandb_run.py:_restore():1507] restore
2021-05-27 12:19:03,587 ERROR   MainThread:34438 [wandb_run.py:_atexit_cleanup():1553] Problem finishing run
Traceback (most recent call last):
  File "/home/veror/Desktop/Uni/Applied Machine Learning/Challenge/ML_project/venv/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1543, in _atexit_cleanup
    self._on_finish()
  File "/home/veror/Desktop/Uni/Applied Machine Learning/Challenge/ML_project/venv/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1695, in _on_finish
    print("")
BrokenPipeError: [Errno 32] Broken pipe
